disabled_rules:
  - line_length
  - type_name
  - type_body_length

opt_in_rules:
  - empty_count
  - force_unwrapping

included:
  - Sources
  - Tests
  - Examples

function_body_length:
  warning: 50
